name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - master
    paths:
      - '*.json'
      - '**.yml'
      - '**/source/**'
      - 'themes/**'
      - '.node-version'
      - 'package-lock.json'
      - 'package.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install Node.js dependencies
        run: |
          npm install
          cd themes/icarus && npm install

      - name: Build
        run: npx hexo clean && npx hexo g

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
